<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastCloner" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tools.Abstraction\Tools.Abstraction.csproj" />
    <ProjectReference Include="..\Tools.Persistence\Tools.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
      <Content Include="Mods\**\*.xml">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
          <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      </Content>
  </ItemGroup>

  <ItemGroup>
  <Compile Update="Mods\ScalingGodPowers\ScalingGodPowersModService.*.cs">
    <DependentUpon>ScalingGodPowersModService.cs</DependentUpon>
  </Compile>
</ItemGroup>

</Project>
