// ReSharper disable IdentifierTypo
// ReSharper disable CommentTypo

namespace Tools.Abstraction.Enum;

public enum GodPowerName
{
    TITAN_GATE, // TitanGate
    CHICKEN_STORM, // ChickenStorm
    WALKING_BERRY_BUSHES, // WalkingBerryBushes
    GOATUNHEIM, // Goatunheim
    CEASE_FIRE3_MINUTES, // CeaseFire3Minutes
    WALKING_WOODS_SINGLE_TARGET, // WalkingWoodsSingleTarget
    CHEAT_METEOR, // CheatMeteor
    BOLT, // Bolt
    SENTINEL, // Sentinel
    LURE, // Lure
    RESTORATION, // Restoration
    CEASE_FIRE, // CeaseFire
    PESTILENCE, // Pestilence
    UNDERWORLD_INVASION, // UnderworldInvasion
    BRONZE, // Bronze
    CURSE, // Curse
    UNDERWORLD_PASSAGE, // UnderworldPassage
    PLENTY_VAULT, // PlentyVault
    LIGHTNING_STORM, // LightningStorm
    EARTHQUAKE, // Earthquake
    WITHER, // Wither
    ARCADIAN_MEADOW, // ArcadianMeadow
    COMMUNAL_HEARTH, // CommunalHearth
    RAIN, // Rain
    PROSPERITY, // Prosperity
    VISION, // Vision
    ECLIPSE, // Eclipse
    SHIFTING_SANDS, // ShiftingSands
    PLAGUE_OF_SERPENTS, // PlagueOfSerpents
    LOCUST_SWARM, // LocustSwarm
    ANCESTORS, // Ancestors
    CITADEL, // Citadel
    SON_OF_OSIRIS, // SonOfOsiris
    METEOR, // Meteor
    TORNADO, // Tornado
    DWARVEN_MINE, // DwarvenMine
    SPY, // Spy
    GREAT_HUNT, // GreatHunt
    GULLINBURSTI, // Gullinbursti
    FOREST_FIRE, // ForestFire
    HEALING_SPRING, // HealingSpring
    UNDERMINE, // Undermine
    ASGARDIAN_BASTION, // AsgardianBastion
    FROST, // Frost
    FLAMING_WEAPONS, // FlamingWeapons
    WALKING_WOODS, // WalkingWoods
    TEMPEST, // Tempest
    RAGNAROK, // Ragnarok
    FIMBULWINTER, // Fimbulwinter
    NIDHOGG, // Nidhogg
    INFERNO, // Inferno
    DECONSTRUCTION, // Deconstruction
    SHOCKWAVE, // Shockwave
    GAIA_FOREST, // GaiaForest
    CARNIVORA, // Carnivora
    VALOR, // Valor
    SPIDER_LAIR, // SpiderLair
    TRAITOR, // Traitor
    CHAOS, // Chaos
    HESPERIDES_TREE, // HesperidesTree
    VORTEX, // Vortex
    TARTARIAN_GATE, // TartarianGate
    IMPLODE, // Implode
    THE_PEACH_BLOSSOM_SPRING, // ThePeachBlossomSpring
    CREATION, // Creation
    PROSPEROUS_SEEDS, // ProsperousSeeds
    LIGHTNING_WEAPONS, // LightningWeapons
    EARTH_WALL, // EarthWall
    VANISH, // Vanish
    FOREST_PROTECTION, // ForestProtection
    DROUGHT_LAND, // DroughtLand
    VENOM_BEAST, // VenomBeast
    GREAT_FLOOD, // GreatFlood
    BLAZING_PRAIRIE, // BlazingPrairie
    YINGLONGS_WRATH, // YinglongsWrath
    VIBRANT_LAND, // VibrantLand
    YIN_AND_YANG, // YinAndYang
    SHIELD_BLESSING, // ShieldBlessing
    GREAT_FLOOD_SPC, // GreatFloodSPC
    REPAIR_PILLAR_SPC, // RepairPillarSPC
    CHANGE_TO_VILLAGER, // ChangeToVillager
    PANDATOPIA, // Pandatopia
    YIN_AND_YANG_TECHREE, // YinAndYangTechree
    SHIELD_BLESSING_TECHREE, // ShieldBlessingTechree
    SPAWN_REWARD_TECHREE, // SpawnRewardTechree
    SOLAR_SHIELD, // SolarShield
    KUSANAGI, // Kusanagi
    NEW_MOON, // NewMoon
    SHRINE_OF_THE_HUNT, // ShrineOfTheHunt
    GOSHINBOKU, // Goshinboku
    SWAMPLAND, // Swampland
    SHOGUN, // Shogun
    SMITING_GUST, // SmitingGust
    THUNDER_BURST, // ThunderBurst
    SACRED_GATE, // SacredGate
    DRAGON_TYPHOON, // DragonTyphoon
    DIVINE_SLASH, // DivineSlash
    BUSHIDO_AMATERASU, // BushidoAmaterasu
    BUSHIDO_TSUKUYOMI, // BushidoTsukuyomi
    BUSHIDO_SUSANOO, // BushidoSusanoo
    AME_NO_UKIHASHI, // AmeNoUkihashi
    HACHIMANS_BLESSING, // HachimansBlessing
    YASUKO_KNOCKBACK, // YasukoKnockback
    FLOWER_GROW, // FlowerGrow
    TREE_CHERRY_GROW, // TreeCherryGrow
    BLOOD_PACT, // BloodPact
    TAILWIND, // Tailwind
    OBSIDIAN_MIRROR, // ObsidianMirror
    LULLABY, // Lullaby
    INFESTATION, // Infestation
    AGAVE_BLOOM, // AgaveBloom
    EARTH_MONSTER, // EarthMonster
    STARFALL, // Starfall
    PURGE, // Purge
    CORRUPTED_GROUND, // CorruptedGround
    MONOLITH_OF_TLALOC, // MonolithOfTlaloc
    VOLCANO, // Volcano
    ANIMAL_SACRIFICE, // AnimalSacrifice
    DEVOTION_FAVOUR_TRICKLE, // DevotionFavourTrickle
}
