// ReSharper disable IdentifierTypo
// ReSharper disable CommentTypo

namespace Tools.Abstraction.Enum;

public enum TechName
{
    ARCHAIC_AGE_WEAKEN_UNITS, // ArchaicAgeWeakenUnits
    ENABLE_RELIC_PICKUP, // EnableRelicPickup
    CLASSICAL_AGE_GENERAL, // ClassicalAgeGeneral
    HEROIC_AGE_GENERAL, // HeroicAgeGeneral
    MYTHIC_AGE_GENERAL, // MythicAgeGeneral
    WONDER_AGE_GENERAL, // WonderAgeGeneral
    WONDER_AGE_JOTUN_SCALE_FIX, // WonderAgeJotunScaleFix
    WONDER_AGE_TITAN, // WonderAgeTitan
    SECRETS_OF_THE_TITANS, // SecretsOfTheTitans
    TECH_TREE_CLASSICAL_AGE, // TechTreeClassicalAge
    TECH_TREE_HEROIC_AGE, // TechTreeHeroicAge
    TECH_TREE_MYTHICAL_AGE, // TechTreeMythicalAge
    DEATH_MATCH_GENERAL, // DeathMatchGeneral
    DEATH_MATCH_GREEK, // DeathMatchGreek
    DEATH_MATCH_EGYPTIAN, // DeathMatchEgyptian
    DEATH_MATCH_NORSE, // DeathMatchNorse
    DEATH_MATCH_ATLANTEAN, // DeathMatchAtlantean
    DEATH_MATCH_CHINESE, // DeathMatchChinese
    DEATHMATCH_NUWA, // DeathmatchNuwa
    DEATH_MATCH_JAPANESE, // DeathMatchJapanese
    LIGHTNING_GENERAL, // LightningGeneral
    STORY_MODE_GENERAL, // StoryModeGeneral
    ARCHAIC_AGE_GREEK, // ArchaicAgeGreek
    CLASSICAL_AGE_GREEK, // ClassicalAgeGreek
    HEROIC_AGE_GREEK, // HeroicAgeGreek
    MYTHIC_AGE_GREEK, // MythicAgeGreek
    ARCHAIC_AGE_ZEUS, // ArchaicAgeZeus
    CLASSICAL_AGE_ZEUS, // ClassicalAgeZeus
    HEROIC_AGE_ZEUS, // HeroicAgeZeus
    MYTHIC_AGE_ZEUS, // MythicAgeZeus
    ARCHAIC_AGE_HADES, // ArchaicAgeHades
    CLASSICAL_AGE_HADES, // ClassicalAgeHades
    HEROIC_AGE_HADES, // HeroicAgeHades
    MYTHIC_AGE_HADES, // MythicAgeHades
    ARCHAIC_AGE_POSEIDON, // ArchaicAgePoseidon
    CLASSICAL_AGE_POSEIDON, // ClassicalAgePoseidon
    HEROIC_AGE_POSEIDON, // HeroicAgePoseidon
    MYTHIC_AGE_POSEIDON, // MythicAgePoseidon
    JASON_ENABLE, // JasonEnable
    OLYMPIAN_PARENTAGE, // OlympianParentage
    AJAX_ENABLE, // AjaxEnable
    VAULTS_OF_EREBUS, // VaultsOfErebus
    THESEUS_ENABLE, // TheseusEnable
    HIPPOCAMPUS_RESPAWN, // HippocampusRespawn
    LORD_OF_HORSES, // LordOfHorses
    CLASSICAL_AGE_ATHENA, // ClassicalAgeAthena
    CLASSICAL_AGE_HERMES, // ClassicalAgeHermes
    CLASSICAL_AGE_ARES, // ClassicalAgeAres
    HEROIC_AGE_DIONYSUS, // HeroicAgeDionysus
    HEROIC_AGE_APOLLO, // HeroicAgeApollo
    HEROIC_AGE_APHRODITE, // HeroicAgeAphrodite
    MYTHIC_AGE_HEPHAESTUS, // MythicAgeHephaestus
    MYTHIC_AGE_HERA, // MythicAgeHera
    MYTHIC_AGE_ARTEMIS, // MythicAgeArtemis
    LABYRINTH_OF_MINOS, // LabyrinthOfMinos
    AEGIS_SHIELD, // AegisShield
    SARISSA, // Sarissa
    SYLVAN_LORE, // SylvanLore
    WINGED_MESSENGER, // WingedMessenger
    WINGED_MESSENGER_RESPAWN, // WingedMessengerRespawn
    SPIRITED_CHARGE, // SpiritedCharge
    PHOBOS_SPEAR_OF_PANIC, // PhobosSpearOfPanic
    DEIMOS_SWORD_OF_DREAD, // DeimosSwordOfDread
    ENYOS_BOW_OF_HORROR, // EnyosBowOfHorror
    WILL_OF_KRONOS, // WillOfKronos
    ORACLE, // Oracle
    TEMPLE_OF_HEALING, // TempleOfHealing
    SUN_RAY, // SunRay
    ANASTROPHE, // Anastrophe
    DIONYSIA, // Dionysia
    THRACIAN_HORSES, // ThracianHorses
    CHTHONIC_RITES, // ChthonicRites
    DIVINE_BLOOD, // DivineBlood
    GOLDEN_APPLES, // GoldenApples
    ROAR_OF_ORTHUS, // RoarOfOrthus
    ARGONAUTS, // Argonauts
    FACE_OF_THE_GORGON, // FaceOfTheGorgon
    MONSTROUS_RAGE, // MonstrousRage
    ARGIVE_PATRONAGE, // ArgivePatronage
    SHAFTS_OF_PLAGUE, // ShaftsOfPlague
    FLAMES_OF_TYPHON, // FlamesOfTyphon
    BEAST_SLAYER, // BeastSlayer
    HAND_OF_TALOS, // HandOfTalos
    SHOULDER_OF_TALOS, // ShoulderOfTalos
    OLYMPIAN_WEAPONS, // OlympianWeapons
    FORGE_OF_OLYMPUS, // ForgeOfOlympus
    LEVY_INFANTRY, // LevyInfantry
    CONSCRIPT_INFANTRY, // ConscriptInfantry
    LEVY_RANGED_SOLDIERS, // LevyRangedSoldiers
    CONSCRIPT_RANGED_SOLDIERS, // ConscriptRangedSoldiers
    LEVY_CAVALRY, // LevyCavalry
    CONSCRIPT_CAVALRY, // ConscriptCavalry
    ARCHAIC_AGE_EGYPTIAN, // ArchaicAgeEgyptian
    CLASSICAL_AGE_EGYPTIAN, // ClassicalAgeEgyptian
    HEROIC_AGE_EGYPTIAN, // HeroicAgeEgyptian
    MYTHIC_AGE_EGYPTIAN, // MythicAgeEgyptian
    MONUMENT_TO_VILLAGERS_SHADOW, // MonumentToVillagersShadow
    MONUMENT_TO_SOLDIERS_SHADOW, // MonumentToSoldiersShadow
    MONUMENT_TO_PRIESTS_SHADOW, // MonumentToPriestsShadow
    MONUMENT_TO_PHARAOHS_SHADOW, // MonumentToPharaohsShadow
    MONUMENT_TO_GODS_SHADOW, // MonumentToGodsShadow
    ARCHAIC_AGE_RA, // ArchaicAgeRa
    CLASSICAL_AGE_RA, // ClassicalAgeRa
    HEROIC_AGE_RA, // HeroicAgeRa
    MYTHIC_AGE_RA, // MythicAgeRa
    ARCHAIC_AGE_ISIS, // ArchaicAgeIsis
    CLASSICAL_AGE_ISIS, // ClassicalAgeIsis
    HEROIC_AGE_ISIS, // HeroicAgeIsis
    MYTHIC_AGE_ISIS, // MythicAgeIsis
    ARCHAIC_AGE_SET, // ArchaicAgeSet
    CLASSICAL_AGE_SET, // ClassicalAgeSet
    HEROIC_AGE_SET, // HeroicAgeSet
    MYTHIC_AGE_SET, // MythicAgeSet
    SKIN_OF_THE_RHINO, // SkinOfTheRhino
    FLOOD_OF_THE_NILE, // FloodOfTheNile
    CLAIRVOYANCE, // Clairvoyance
    CLASSICAL_AGE_ANUBIS, // ClassicalAgeAnubis
    CLASSICAL_AGE_BAST, // ClassicalAgeBast
    CLASSICAL_AGE_PTAH, // ClassicalAgePtah
    HEROIC_AGE_SEKHMET, // HeroicAgeSekhmet
    HEROIC_AGE_SOBEK, // HeroicAgeSobek
    HEROIC_AGE_NEPHTHYS, // HeroicAgeNephthys
    MYTHIC_AGE_OSIRIS, // MythicAgeOsiris
    MYTHIC_AGE_HORUS, // MythicAgeHorus
    MYTHIC_AGE_THOTH, // MythicAgeThoth
    FEET_OF_THE_JACKAL, // FeetOfTheJackal
    NECROPOLIS, // Necropolis
    SERPENT_SPEAR, // SerpentSpear
    SHADUF, // Shaduf
    SCALLOPED_AXE, // ScallopedAxe
    LEATHER_FRAME_SHIELD, // LeatherFrameShield
    ELECTRUM_BULLETS, // ElectrumBullets
    ADZE_OF_WEPWAWET, // AdzeOfWepwawet
    SACRED_CATS, // SacredCats
    CRIOSPHINX, // Criosphinx
    HIERACOSPHINX, // Hieracosphinx
    BONE_BOW, // BoneBow
    SLINGS_OF_THE_SUN, // SlingsOfTheSun
    FORCE_OF_THE_WEST_WIND, // ForceOfTheWestWind
    CRIMSON_LINEN, // CrimsonLinen
    SUN_DRIED_MUD_BRICK, // SunDriedMudBrick
    CROCODILOPOLIS, // Crocodilopolis
    DARK_WATER, // DarkWater
    SOLAR_BARQUE, // SolarBarque
    SPIRIT_OF_MAAT, // SpiritOfMaat
    FUNERAL_RITES, // FuneralRites
    NEBTY, // Nebty
    FUNERAL_BARGE, // FuneralBarge
    ATEF_CROWN, // AtefCrown
    NEW_KINGDOM, // NewKingdom
    NEW_KINGDOM_PHARAOH_RESPAWN, // NewKingdomPharaohRespawn
    DESERT_WIND, // DesertWind
    BOOK_OF_THOTH, // BookOfThoth
    TUSKS_OF_APEDEMAK, // TusksOfApedemak
    VALLEY_OF_THE_KINGS, // ValleyOfTheKings
    AXE_OF_VENGEANCE, // AxeOfVengeance
    GREATEST_OF_FIFTY, // GreatestOfFifty
    SPEAR_OF_HORUS, // SpearOfHorus
    MEDIUM_AXEMEN, // MediumAxemen
    HEAVY_AXEMEN, // HeavyAxemen
    CHAMPION_AXEMEN, // ChampionAxemen
    MEDIUM_SPEARMEN, // MediumSpearmen
    HEAVY_SPEARMEN, // HeavySpearmen
    CHAMPION_SPEARMEN, // ChampionSpearmen
    MEDIUM_SLINGERS, // MediumSlingers
    HEAVY_SLINGERS, // HeavySlingers
    CHAMPION_SLINGERS, // ChampionSlingers
    LEVY_BARRACKS_SOLDIERS, // LevyBarracksSoldiers
    CONSCRIPT_BARRACKS_SOLDIERS, // ConscriptBarracksSoldiers
    MEDIUM_CHARIOT_ARCHERS, // MediumChariotArchers
    HEAVY_CHARIOT_ARCHERS, // HeavyChariotArchers
    CHAMPION_CHARIOT_ARCHERS, // ChampionChariotArchers
    MEDIUM_CAMEL_RIDERS, // MediumCamelRiders
    HEAVY_CAMEL_RIDERS, // HeavyCamelRiders
    CHAMPION_CAMEL_RIDERS, // ChampionCamelRiders
    MEDIUM_WAR_ELEPHANTS, // MediumWarElephants
    HEAVY_WAR_ELEPHANTS, // HeavyWarElephants
    CHAMPION_WAR_ELEPHANTS, // ChampionWarElephants
    LEVY_MIGDOL_SOLDIERS, // LevyMigdolSoldiers
    CONSCRIPT_MIGDOL_SOLDIERS, // ConscriptMigdolSoldiers
    PRIEST_ENABLE_REAL, // PriestEnableReal
    PHARAOH_FIRST_SPAWN, // PharaohFirstSpawn
    PHARAOH_RESPAWN, // PharaohRespawn
    HANDS_OF_THE_PHARAOH, // HandsOfThePharaoh
    CITADEL_WALL, // CitadelWall
    BALLISTA_TOWER, // BallistaTower
    ARCHAIC_AGE_NORSE, // ArchaicAgeNorse
    CLASSICAL_AGE_NORSE, // ClassicalAgeNorse
    HEROIC_AGE_NORSE, // HeroicAgeNorse
    MYTHIC_AGE_NORSE, // MythicAgeNorse
    ARCHAIC_AGE_THOR, // ArchaicAgeThor
    CLASSICAL_AGE_THOR, // ClassicalAgeThor
    HEROIC_AGE_THOR, // HeroicAgeThor
    MYTHIC_AGE_THOR, // MythicAgeThor
    ARCHAIC_AGE_ODIN, // ArchaicAgeOdin
    CLASSICAL_AGE_ODIN, // ClassicalAgeOdin
    HEROIC_AGE_ODIN, // HeroicAgeOdin
    MYTHIC_AGE_ODIN, // MythicAgeOdin
    RAVEN_RESPAWN, // RavenRespawn
    RAVEN_FIRST_SPAWN, // RavenFirstSpawn
    ARCHAIC_AGE_LOKI, // ArchaicAgeLoki
    CLASSICAL_AGE_LOKI, // ClassicalAgeLoki
    HEROIC_AGE_LOKI, // HeroicAgeLoki
    MYTHIC_AGE_LOKI, // MythicAgeLoki
    ARCHAIC_AGE_FREYR, // ArchaicAgeFreyr
    FREYR_TECH_COST_BONUS, // FreyrTechCostBonus
    CLASSICAL_AGE_FREYR, // ClassicalAgeFreyr
    HEROIC_AGE_FREYR, // HeroicAgeFreyr
    MYTHIC_AGE_FREYR, // MythicAgeFreyr
    THOR_DWARF_SPAWN, // ThorDwarfSpawn
    HAMMER_OF_THUNDER, // HammerOfThunder
    DWARVEN_WEAPONS, // DwarvenWeapons
    METEORIC_IRON_ARMOR, // MeteoricIronArmor
    DRAGONSCALE_SHIELDS, // DragonscaleShields
    HAMASK, // Hamask
    EYES_IN_THE_FOREST, // EyesInTheForest
    FREYRS_GIFT, // FreyrsGift
    CLASSICAL_AGE_FREYJA, // ClassicalAgeFreyja
    CLASSICAL_AGE_FORSETI, // ClassicalAgeForseti
    CLASSICAL_AGE_HEIMDALL, // ClassicalAgeHeimdall
    CLASSICAL_AGE_ULLR, // ClassicalAgeUllr
    ULLR_HUSKARL_SHADOW, // UllrHuskarlShadow
    ASGARDIAN_BASTION_SHADOW_HEROIC, // AsgardianBastionShadowHeroic
    ASGARDIAN_BASTION_SHADOW_MYTHIC, // AsgardianBastionShadowMythic
    HEROIC_AGE_BRAGI, // HeroicAgeBragi
    HEROIC_AGE_SKADI, // HeroicAgeSkadi
    HEROIC_AGE_NJORD, // HeroicAgeNjord
    HEROIC_AGE_AEGIR, // HeroicAgeAegir
    MYTHIC_AGE_HEL, // MythicAgeHel
    MYTHIC_AGE_BALDR, // MythicAgeBaldr
    MYTHIC_AGE_TYR, // MythicAgeTyr
    MYTHIC_AGE_VIDAR, // MythicAgeVidar
    DISABLOT, // Disablot
    THUNDERING_HOOVES, // ThunderingHooves
    SESSRUMNIR, // Sessrumnir
    CAVE_TROLL, // CaveTroll
    HALL_OF_THANES, // HallOfThanes
    DWARVEN_BREASTPLATE, // DwarvenBreastplate
    GJALLARHORN, // Gjallarhorn
    SAFEGUARD, // Safeguard
    RIGSTHULA, // Rigsthula
    VALGALDR, // Valgaldr
    SERVANTS_OF_GLORY, // ServantsOfGlory
    RING_OATH, // RingOath
    YDALIR, // Ydalir
    CALL_OF_VALHALLA, // CallOfValhalla
    THURISAZ_RUNE, // ThurisazRune
    SWINE_ARRAY, // SwineArray
    LONG_SERPENT, // LongSerpent
    RIME, // Rime
    HUNTRESS_AXE, // HuntressAxe
    WINTER_HARVEST, // WinterHarvest
    ARCTIC_WINDS, // ArcticWinds
    JOTUNS, // Jotuns
    RING_GIVER, // RingGiver
    VIKINGS, // Vikings
    WRATH_OF_THE_DEEP, // WrathOfTheDeep
    GRANITE_MAW, // GraniteMaw
    FEASTS_OF_RENOWN, // FeastsOfRenown
    NINE_WAVES, // NineWaves
    GRASP_OF_RAN, // GraspOfRan
    RAMPAGE, // Rampage
    GRANITE_BLOOD, // GraniteBlood
    SONS_OF_SLEIPNIR, // SonsOfSleipnir
    DWARVEN_AUGER, // DwarvenAuger
    BERSERKERGANG, // Berserkergang
    BRAVERY, // Bravery
    TWILIGHT_OF_THE_GODS, // TwilightOfTheGods
    AVENGING_SPIRIT, // AvengingSpirit
    SILENT_RESOLVE, // SilentResolve
    FURY_OF_THE_FALLEN, // FuryOfTheFallen
    LEVY_LONGHOUSE_SOLDIERS, // LevyLonghouseSoldiers
    CONSCRIPT_LONGHOUSE_SOLDIERS, // ConscriptLonghouseSoldiers
    LEVY_GREAT_HALL_SOLDIERS, // LevyGreatHallSoldiers
    CONSCRIPT_GREAT_HALL_SOLDIERS, // ConscriptGreatHallSoldiers
    LEVY_HILL_FORT_SOLDIERS, // LevyHillFortSoldiers
    CONSCRIPT_HILL_FORT_SOLDIERS, // ConscriptHillFortSoldiers
    ARCHAIC_AGE_ATLANTEAN, // ArchaicAgeAtlantean
    CLASSICAL_AGE_ATLANTEAN, // ClassicalAgeAtlantean
    HEROIC_AGE_ATLANTEAN, // HeroicAgeAtlantean
    MYTHIC_AGE_ATLANTEAN, // MythicAgeAtlantean
    ARCHAIC_AGE_KRONOS, // ArchaicAgeKronos
    KRONOS_EXTRA_PROMETHEAN, // KronosExtraPromethean
    KRONOS_EXTRA_AUTOMATON, // KronosExtraAutomaton
    CLASSICAL_AGE_KRONOS, // ClassicalAgeKronos
    KRONOS_EXTRA_BEHEMOTH, // KronosExtraBehemoth
    KRONOS_EXTRA_SATYR, // KronosExtraSatyr
    HEROIC_AGE_KRONOS, // HeroicAgeKronos
    KRONOS_EXTRA_ARGUS, // KronosExtraArgus
    KRONOS_EXTRA_CENTIMANUS, // KronosExtraCentimanus
    MYTHIC_AGE_KRONOS, // MythicAgeKronos
    ARCHAIC_AGE_ORANOS, // ArchaicAgeOranos
    CLASSICAL_AGE_ORANOS, // ClassicalAgeOranos
    HEROIC_AGE_ORANOS, // HeroicAgeOranos
    MYTHIC_AGE_ORANOS, // MythicAgeOranos
    ARCHAIC_AGE_GAIA, // ArchaicAgeGaia
    CLASSICAL_AGE_GAIA, // ClassicalAgeGaia
    HEROIC_AGE_GAIA, // HeroicAgeGaia
    MYTHIC_AGE_GAIA, // MythicAgeGaia
    TEMPORAL_CHAOS, // TemporalChaos
    EMPYREAN_SPEED, // EmpyreanSpeed
    CHANNELS, // Channels
    CLASSICAL_AGE_PROMETHEUS, // ClassicalAgePrometheus
    CLASSICAL_AGE_OCEANUS, // ClassicalAgeOceanus
    CLASSICAL_AGE_LETO, // ClassicalAgeLeto
    HEROIC_AGE_HYPERION, // HeroicAgeHyperion
    HEROIC_AGE_THEIA, // HeroicAgeTheia
    HEROIC_AGE_RHEIA, // HeroicAgeRheia
    MYTHIC_AGE_HEKATE, // MythicAgeHekate
    MYTHIC_AGE_HELIOS, // MythicAgeHelios
    MYTHIC_AGE_ATLAS, // MythicAgeAtlas
    ALLUVIAL_CLAY, // AlluvialClay
    HEART_OF_THE_TITANS, // HeartOfTheTitans
    THEFT_OF_FIRE, // TheftOfFire
    BITE_OF_THE_SHARK, // BiteOfTheShark
    WEIGHTLESS_MACE, // WeightlessMace
    FRONTLINE_HEROICS, // FrontlineHeroics
    HEPHAESTUS_REVENGE, // HephaestusRevenge
    VOLCANIC_FORGE, // VolcanicForge
    PERCEPTION, // Perception
    GEMINI, // Gemini
    HEROIC_RENEWAL, // HeroicRenewal
    SONS_OF_THE_SUN, // SonsOfTheSun
    PIONEER_OF_THE_SKIES, // PioneerOfTheSkies
    PROPHETIC_SIGHT, // PropheticSight
    POSEIDONS_SECRET, // PoseidonsSecret
    LANCE_OF_STONE, // LanceOfStone
    DAUGHTERS_OF_THE_SEA, // DaughtersOfTheSea
    HORNS_OF_CONSECRATION, // HornsOfConsecration
    ORICHALCUM_MAIL, // OrichalcumMail
    RHEIAS_GIFT, // RheiasGift
    DAKTYLOI, // Daktyloi
    ASPER_BLOOD, // AsperBlood
    MYTHIC_REJUVENATION, // MythicRejuvenation
    CELERITY, // Celerity
    HALO_OF_THE_SUN, // HaloOfTheSun
    PETRIFICATION, // Petrification
    TITANOMACHY, // Titanomachy
    GUARDIAN_OF_IO, // GuardianOfIo
    DEVOTEES_OF_ATLAS, // DevoteesOfAtlas
    TITAN_SHIELD, // TitanShield
    BRONZE_WALL, // BronzeWall
    IRON_WALL, // IronWall
    ORICHALCUM_WALL, // OrichalcumWall
    LEVY_MAINLINE_SOLDIERS, // LevyMainlineSoldiers
    CONSCRIPT_MAINLINE_SOLDIERS, // ConscriptMainlineSoldiers
    LEVY_COUNTER_SOLDIERS, // LevyCounterSoldiers
    CONSCRIPT_COUNTER_SOLDIERS, // ConscriptCounterSoldiers
    LEVY_PALACE_SOLDIERS, // LevyPalaceSoldiers
    CONSCRIPT_PALACE_SOLDIERS, // ConscriptPalaceSoldiers
    ARCHAIC_AGE_CHINESE, // ArchaicAgeChinese
    CLASSICAL_AGE_CHINESE, // ClassicalAgeChinese
    HEROIC_AGE_CHINESE, // HeroicAgeChinese
    MYTHIC_AGE_CHINESE, // MythicAgeChinese
    ARCHAIC_AGE_FUXI, // ArchaicAgeFuxi
    CLASSICAL_AGE_FUXI, // ClassicalAgeFuxi
    HEROIC_AGE_FUXI, // HeroicAgeFuxi
    MYTHIC_AGE_FUXI, // MythicAgeFuxi
    ARCHAIC_AGE_NUWA, // ArchaicAgeNuwa
    CLASSICAL_AGE_NUWA, // ClassicalAgeNuwa
    HEROIC_AGE_NUWA, // HeroicAgeNuwa
    MYTHIC_AGE_NUWA, // MythicAgeNuwa
    ARCHAIC_AGE_SHENNONG, // ArchaicAgeShennong
    CLASSICAL_AGE_SHENNONG, // ClassicalAgeShennong
    HEROIC_AGE_SHENNONG, // HeroicAgeShennong
    MYTHIC_AGE_SHENNONG, // MythicAgeShennong
    TAI_CHI, // TaiChi
    CELESTIAL_WEAPONS, // CelestialWeapons
    MOUNTAINOUS_MIGHT, // MountainousMight
    KUAFU_CHIEFTAIN, // KuafuChieftain
    HERO_KUAFU_RESPAWN, // HeroKuafuRespawn
    HERBAL_MEDICINE, // HerbalMedicine
    PEACH_OF_IMMORTALITY, // PeachOfImmortality
    DISABLE_BUILDING_CHAIN, // DisableBuildingChain
    CLASSICAL_AGE_XUANNU, // ClassicalAgeXuannu
    CLASSICAL_AGE_CHIYOU, // ClassicalAgeChiyou
    CLASSICAL_AGE_HOUTU, // ClassicalAgeHoutu
    HEROIC_AGE_GOUMANG, // HeroicAgeGoumang
    HEROIC_AGE_NUBA, // HeroicAgeNuba
    HEROIC_AGE_RUSHOU, // HeroicAgeRushou
    MYTHIC_AGE_GONGGONG, // MythicAgeGonggong
    MYTHIC_AGE_HUANGDI, // MythicAgeHuangdi
    MYTHIC_AGE_ZHURONG, // MythicAgeZhurong
    REINCARNATION, // Reincarnation
    DIVINE_BOOKS, // DivineBooks
    QI_LINS_BLESSING, // QiLinsBlessing
    QILIN_PASSIVE_ABILITY_SHADOW, // QilinPassiveAbilityShadow
    MASTER_OF_WEAPONRY, // MasterOfWeaponry
    SPOILS_OF_WAR, // SpoilsOfWar
    SON_OF_LOONG, // SonOfLoong
    RAGE_OF_SLAUGHTER, // RageOfSlaughter
    ADVANCED_DEFENSES, // AdvancedDefenses
    ABUNDANCE, // Abundance
    CHASING_THE_SUN, // ChasingTheSun
    SINISTER_DEFIANCE, // SinisterDefiance
    VIBRANT_LAND, // VibrantLand
    HOOVES_OF_THE_WIND, // HoovesOfTheWind
    MAELSTROM, // Maelstrom
    FRENZIED_DASH, // FrenziedDash
    SCORCHING_FEATHERS, // ScorchingFeathers
    ROCK_SOLID, // RockSolid
    DROUGHT_SHIPS, // DroughtShips
    BOTTOMLESS_STOMACH, // BottomlessStomach
    GILDED_SHIELDS, // GildedShields
    DIVINE_JUDGEMENT, // DivineJudgement
    AUTUMN_OF_ABUNDANCE, // AutumnOfAbundance
    RED_CLIFFS_FLEET, // RedCliffsFleet
    SHAKER_OF_HEAVEN, // ShakerOfHeaven
    TEMPESTUOUS_STORM, // TempestuousStorm
    LAST_STAND, // LastStand
    RISING_TIDE, // RisingTide
    XUANYUANS_BLOODLINE, // XuanyuansBloodline
    IMPERIAL_ORDER, // ImperialOrder
    LEIZUS_SILK, // LeizusSilk
    POWER_OF_CHAOS, // PowerOfChaos
    SOUTHERN_FIRE, // SouthernFire
    SLASH_AND_BURN, // SlashAndBurn
    FLAMING_BLOOD, // FlamingBlood
    SONG_OF_MIDSUMMER, // SongOfMidsummer
    LEVY_BAOLEI_SOLDIERS, // LevyBaoleiSoldiers
    CONSCRIPT_BAOLEI_SOLDIERS, // ConscriptBaoleiSoldiers
    DIVINE_LIGHT, // DivineLight
    EAST_WIND, // EastWind
    SKY_FIRE, // SkyFire
    SILK_ROAD, // SilkRoad
    GREAT_WALL, // GreatWall
    CROSSBOW_TOWER, // CrossbowTower
    FISH_BASKET, // FishBasket
    TERRACOTTA_RIDERS, // TerracottaRiders
    ARCHAIC_AGE_JAPANESE, // ArchaicAgeJapanese
    CLASSICAL_AGE_JAPANESE, // ClassicalAgeJapanese
    HEROIC_AGE_JAPANESE, // HeroicAgeJapanese
    MYTHIC_AGE_JAPANESE, // MythicAgeJapanese
    ARCHAIC_AGE_AMATERASU, // ArchaicAgeAmaterasu
    CLASSICAL_AGE_AMATERASU, // ClassicalAgeAmaterasu
    HEROIC_AGE_AMATERASU, // HeroicAgeAmaterasu
    MYTHIC_AGE_AMATERASU, // MythicAgeAmaterasu
    ARCHAIC_AGE_TSUKUYOMI, // ArchaicAgeTsukuyomi
    CLASSICAL_AGE_TSUKUYOMI, // ClassicalAgeTsukuyomi
    HEROIC_AGE_TSUKUYOMI, // HeroicAgeTsukuyomi
    MYTHIC_AGE_TSUKUYOMI, // MythicAgeTsukuyomi
    ARCHAIC_AGE_SUSANOO, // ArchaicAgeSusanoo
    CLASSICAL_AGE_SUSANOO, // ClassicalAgeSusanoo
    HEROIC_AGE_SUSANOO, // HeroicAgeSusanoo
    MYTHIC_AGE_SUSANOO, // MythicAgeSusanoo
    KAGURA, // Kagura
    TENSHU, // Tenshu
    CRUSHING_WAVES, // CrushingWaves
    CLASSICAL_AGE_INARI_OKAMI, // ClassicalAgeInariOkami
    CLASSICAL_AGE_AME_NO_UZUME, // ClassicalAgeAmeNoUzume
    CLASSICAL_AGE_MINAKATATOMI, // ClassicalAgeMinakatatomi
    HEROIC_AGE_HACHIMAN, // HeroicAgeHachiman
    HEROIC_AGE_RAIJIN, // HeroicAgeRaijin
    HEROIC_AGE_FUJIN, // HeroicAgeFujin
    MYTHIC_AGE_TAKEMIKAZUCHI, // MythicAgeTakemikazuchi
    MYTHIC_AGE_WATATSUMI, // MythicAgeWatatsumi
    MYTHIC_AGE_OKUNINUSHI, // MythicAgeOkuninushi
    DEADLY_SNARE, // DeadlySnare
    WISDOM_OF_NINE, // WisdomOfNine
    SASHIMONO_BANNERMEN, // SashimonoBannermen
    IVORY_NETSUKE, // IvoryNetsuke
    WIND_SICKLES, // WindSickles
    KATAGI, // Katagi
    GOHEI_WANDS, // GoheiWands
    CONDEMNED_SOUL, // CondemnedSoul
    SALTWATER_SPRING, // SaltwaterSpring
    HUNTERS_STRENGTH, // HuntersStrength
    KUMIKI, // Kumiki
    ASCETIC_PRACTICES, // AsceticPractices
    GOLDEN_KITE, // GoldenKite
    EIGHT_BANNERS, // EightBanners
    DAN_NO_URA_TACTICS, // DanNoUraTactics
    THUNDEROUS_PRESENCE, // ThunderousPresence
    DEN_DEN_DRUMS, // DenDenDrums
    HANNYA_MASK, // HannyaMask
    HEAVENLY_BARRAGE, // HeavenlyBarrage
    DEADLY_RAGE, // DeadlyRage
    ONI_MASK, // OniMask
    GALES_FURY, // GalesFury
    BURNING_MALEVOLENCE, // BurningMalevolence
    SUMO_TRAINING, // SumoTraining
    TEN_FIST_SWORD, // TenFistSword
    SOJUTSU, // Sojutsu
    RESTLESS_ARMY, // RestlessArmy
    DIVINE_PREFECTURE, // DivinePrefecture
    MECHANICAL_ARTISANS, // MechanicalArtisans
    ETERNAL_HAUNTING, // EternalHaunting
    SEASIDE_INFILTRATORS, // SeasideInfiltrators
    ONMYODO, // Onmyodo
    ASYMMETRICAL_BOWS, // AsymmetricalBows
    MEDIUM_GUARDHOUSE_SOLDIERS, // MediumGuardhouseSoldiers
    HEAVY_GUARDHOUSE_SOLDIERS, // HeavyGuardhouseSoldiers
    CHAMPION_GUARDHOUSE_SOLDIERS, // ChampionGuardhouseSoldiers
    LEVY_GUARDHOUSE_SOLDIERS, // LevyGuardhouseSoldiers
    CONSCRIPT_GUARDHOUSE_SOLDIERS, // ConscriptGuardhouseSoldiers
    MEDIUM_STABLE_SOLDIERS, // MediumStableSoldiers
    HEAVY_STABLE_SOLDIERS, // HeavyStableSoldiers
    CHAMPION_STABLE_SOLDIERS, // ChampionStableSoldiers
    LEVY_STABLE_SOLDIERS, // LevyStableSoldiers
    CONSCRIPT_STABLE_SOLDIERS, // ConscriptStableSoldiers
    MEDIUM_DOJO_SOLDIERS, // MediumDojoSoldiers
    HEAVY_DOJO_SOLDIERS, // HeavyDojoSoldiers
    CHAMPION_DOJO_SOLDIERS, // ChampionDojoSoldiers
    ELITE_DOJO_SOLDIERS, // EliteDojoSoldiers
    LEVY_DOJO_SOLDIERS, // LevyDojoSoldiers
    CONSCRIPT_DOJO_SOLDIERS, // ConscriptDojoSoldiers
    SACRED_CUSTODIANS_ENABLE, // SacredCustodiansEnable
    SACRED_CUSTODIANS, // SacredCustodians
    SAKURA_GARDENS, // SakuraGardens
    MASONS, // Masons
    ARCHITECTS, // Architects
    FORTIFIED_TOWN_CENTER, // FortifiedTownCenter
    HUSBANDRY, // Husbandry
    HUNTING_EQUIPMENT, // HuntingEquipment
    PLOW, // Plow
    IRRIGATION, // Irrigation
    FLOOD_CONTROL, // FloodControl
    HAND_AXE, // HandAxe
    BOW_SAW, // BowSaw
    CARPENTERS, // Carpenters
    PICKAXE, // Pickaxe
    SHAFT_MINE, // ShaftMine
    QUARRY, // Quarry
    TAX_COLLECTORS, // TaxCollectors
    AMBASSADORS, // Ambassadors
    COINAGE, // Coinage
    PURSE_SEINE, // PurseSeine
    SALT_AMPHORA, // SaltAmphora
    ENCLOSED_DECK, // EnclosedDeck
    HEROIC_FLEET, // HeroicFleet
    HEAVY_WARSHIPS, // HeavyWarships
    CHAMPION_WARSHIPS, // ChampionWarships
    CONSCRIPT_SAILORS, // ConscriptSailors
    STONE_WALL, // StoneWall
    FORTIFIED_WALL, // FortifiedWall
    WATCH_TOWER, // WatchTower
    GUARD_TOWER, // GuardTower
    SIGNAL_FIRES, // SignalFires
    CARRIER_PIGEONS, // CarrierPigeons
    CRENELLATIONS, // Crenellations
    BOILING_OIL, // BoilingOil
    OMNISCIENCE, // Omniscience
    COPPER_WEAPONS, // CopperWeapons
    BRONZE_WEAPONS, // BronzeWeapons
    IRON_WEAPONS, // IronWeapons
    COPPER_ARMOR, // CopperArmor
    BRONZE_ARMOR, // BronzeArmor
    IRON_ARMOR, // IronArmor
    COPPER_SHIELDS, // CopperShields
    BRONZE_SHIELDS, // BronzeShields
    IRON_SHIELDS, // IronShields
    BURNING_PITCH, // BurningPitch
    BALLISTICS, // Ballistics
    MEDIUM_INFANTRY, // MediumInfantry
    HEAVY_INFANTRY, // HeavyInfantry
    CHAMPION_INFANTRY, // ChampionInfantry
    MEDIUM_ARCHERS, // MediumArchers
    HEAVY_ARCHERS, // HeavyArchers
    CHAMPION_ARCHERS, // ChampionArchers
    MEDIUM_CAVALRY, // MediumCavalry
    HEAVY_CAVALRY, // HeavyCavalry
    CHAMPION_CAVALRY, // ChampionCavalry
    DRAFT_HORSES, // DraftHorses
    ENGINEERS, // Engineers
    ADVANCED_FORTIFICATIONS, // AdvancedFortifications
    RELIC_ANKHOF_RA, // RelicAnkhofRa
    RELIC_EYE_OF_HORUS, // RelicEyeOfHorus
    RELIC_SISTRUM_OF_BAST, // RelicSistrumOfBast
    RELIC_HEAD_OF_ORPHEUS, // RelicHeadOfOrpheus
    RELIC_RING_OF_NIBELUNG, // RelicRingOfNibelung
    RELIC_STAFF_OF_DIONYSUS, // RelicStaffOfDionysus
    RELIC_FETTERS_OF_FENRIR, // RelicFettersOfFenrir
    RELIC_GUNGNIR_ODINS_SPEAR, // RelicGungnirOdinsSpear
    RELIC_KITHARA_OF_APOLLO, // RelicKitharaOfApollo
    RELIC_DWARVEN_HORSESHOES, // RelicDwarvenHorseshoes
    RELIC_BOW_OF_ARTEMIS, // RelicBowOfArtemis
    RELIC_SCALES_OF_ECHIDNA, // RelicScalesOfEchidna
    RELIC_NOSE_OF_THE_SPHINX, // RelicNoseOfTheSphinx
    RELIC_ARROWS_OF_ALFAR, // RelicArrowsOfAlfar
    RELIC_ARROWS_OF_HERACLES, // RelicArrowsOfHeracles
    RELIC_GAMBANTEINN_ODINS_WAND, // RelicGambanteinnOdinsWand
    RELIC_BRIDLE_OF_PEGASUS, // RelicBridleOfPegasus
    BRIDLE_OF_PEGASUS_RESPAWN, // BridleOfPegasusRespawn
    RELIC_ULLRS_BOW, // RelicUllrsBow
    RELIC_BLUE_CRYSTAL_SHARD, // RelicBlueCrystalShard
    RELIC_ARMOR_OF_ACHILLES, // RelicArmorOfAchilles
    RELIC_SHIP_OF_FINGERNAILS, // RelicShipOfFingernails
    RELIC_ADAMANTITE_SHINGLES, // RelicAdamantiteShingles
    RELIC_EYE_OF_ORNLU, // RelicEyeOfOrnlu
    RELIC_TUSK_OF_THE_IRON_BOAR, // RelicTuskOfTheIronBoar
    RELIC_PANDORAS_BOX, // RelicPandorasBox
    RELIC_THUNDERCLOUD_SHAWL, // RelicThundercloudShawl
    RELIC_HARMONIAS_NECKLACE, // RelicHarmoniasNecklace
    RELIC_DWARVEN_CALIPERS, // RelicDwarvenCalipers
    RELIC_CHARIOT_OF_CYBELE, // RelicChariotOfCybele
    GOLDEN_LIONS_RESPAWN, // GoldenLionsRespawn
    RELIC_SKULLS_OF_THE_CERCOPES, // RelicSkullsOfTheCercopes
    RELIC_MONKEY_RESPAWN, // RelicMonkeyRespawn
    RELIC_CANOPIC_JAR_OF_IMSETY, // RelicCanopicJarOfImsety
    RELIC_TOWER_OF_SESTUS, // RelicTowerOfSestus
    RELIC_TROJAN_GATE_HINGE, // RelicTrojanGateHinge
    RELIC_GIRDLE_OF_HIPPOLYTA, // RelicGirdleOfHippolyta
    RELIC_PYGMALIONS_STATUE, // RelicPygmalionsStatue
    RELIC_BLACK_LOTUS, // RelicBlackLotus
    RELIC_HARTERS_FOLLY, // RelicHartersFolly
    RELIC_SCARAB_PENDANT, // RelicScarabPendant
    RELIC_HERMES_WINGED_SANDALS, // RelicHermesWingedSandals
    RELIC_ANVIL_OF_HEPHAESTUS, // RelicAnvilOfHephaestus
    RELIC_PELT_OF_ARGUS, // RelicPeltOfArgus
    RELIC_OSEBERG_WAGON, // RelicOsebergWagon
    RELIC_FLAGSTONE_OF_BUHEN, // RelicFlagstoneOfBuhen
    RELIC_SCALES_OF_CATOBLEPAS, // RelicScalesOfCatoblepas
    RELIC_TAIL_OF_CERBERUS, // RelicTailOfCerberus
    RELIC_BLANKET_OF_EMPRESS_ZOE, // RelicBlanketOfEmpressZoe
    RELIC_KHOPESH_OF_HORUS, // RelicKhopeshOfHorus
    RELIC_TITANS_TREASURE, // RelicTitansTreasure
    RELIC_GAIAS_BOOK_OF_KNOWLEDGE, // RelicGaiasBookOfKnowledge
    RELIC_ARCHIMEDES_LEDGER, // RelicArchimedesLedger
    RELIC_DEMETERS_THRONE, // RelicDemetersThrone
    RELIC_HESTIAS_HEARTH, // RelicHestiasHearth
    RELIC_PTAHS_SCEPTRE, // RelicPtahsSceptre
    RELIC_TYRFING_ANGANTYRS_SWORD, // RelicTyrfingAngantyrsSword
    RELIC_SVADILFARIS_SLEDGE, // RelicSvadilfarisSledge
    RELIC_RHEIAS_CROWN, // RelicRheiasCrown
    RELIC_TEXTS_OF_IMHOTEP, // RelicTextsOfImhotep
    RELIC_CHARONS_OBOL, // RelicCharonsObol
    RELIC_HEKATES_TORCHES, // RelicHekatesTorches
    RELIC_XIRANG, // RelicXirang
    RELIC_JADE_HARE, // RelicJadeHare
    RELIC_FEATHER_OF_JINGWEI, // RelicFeatherOfJingwei
    RELIC_TUSK_OF_DANGKANG, // RelicTuskOfDangkang
    TUSK_OF_DANGKANG_SPAWN, // TuskOfDangkangSpawn
    RELIC_TAIL_OF_FEI, // RelicTailOfFei
    TAIL_OF_FEI_RESPAWN, // TailOfFeiRespawn
    RELIC_FEATHER_OF_BIFANG, // RelicFeatherOfBifang
    RELIC_WUHAO_BOW_OF_HUANGDI, // RelicWuhaoBowOfHuangdi
    RELIC_FUR_OF_BOYI, // RelicFurOfBoyi
    RELIC_NINE_CAULDRONS, // RelicNineCauldrons
    RELIC_OCHRE_WHIP_OF_SHENNONG, // RelicOchreWhipOfShennong
    PLOW_BONUS, // PlowBonus
    IRRIGATION_BONUS, // IrrigationBonus
    FLOOD_CONTROL_BONUS, // FloodControlBonus
    RELIC_FIVE_COLORED_STONE_OF_NUWA, // RelicFiveColoredStoneOfNuwa
    RELIC_KUI_DRUM, // RelicKuiDrum
    RELIC_TAIL_FEATHERS_OF_HEAVEN, // RelicTailFeathersOfHeaven
    RELIC_LITTLE_CROW_CIRCLE, // RelicLittleCrowCircle
    RELIC_HEAVENLY_JEWELED_SPEAR, // RelicHeavenlyJeweledSpear
    RELIC_OKUNINUSHIS_COVENANT, // RelicOkuninushisCovenant
    RELIC_HOORIS_HUNTING_BOW, // RelicHoorisHuntingBow
    RELIC_NINE_TAILED_FOX_CHARM, // RelicNineTailedFoxCharm
    RELIC_GRASS_CUTTING_SWORD, // RelicGrassCuttingSword
    RELIC_TAWARA_TODAS_LAST_ARROW, // RelicTawaraTodasLastArrow
    RELIC_OGRE_BITTEN_HELM, // RelicOgreBittenHelm
    RELIC_DRAGON_PALACE_CRYSTAL, // RelicDragonPalaceCrystal
    RELIC_AME_NO_MURAKUMO_NO_TSURUGI, // RelicAmeNoMurakumoNoTsurugi
    RELIC_SHEN_OF_NEKHBET, // RelicShenOfNekhbet
    RELIC_CUP_OF_DIONYSUS, // RelicCupOfDionysus
    RELIC_SHIELD_OF_ATHENA, // RelicShieldOfAthena
    RELIC_CROWN_OF_HERA, // RelicCrownOfHera
    RELIC_ZEUS_THUNDERBOLTS, // RelicZeusThunderbolts
    RELIC_RELIC_OF_PROSPERITY, // RelicRelicOfProsperity
    RELIC_RELIC_OF_BRONZE, // RelicRelicOfBronze
    RELIC_RELIC_OF_EARTHQUAKE, // RelicRelicOfEarthquake
    RELIC_RELIC_OF_ANCESTORS, // RelicRelicOfAncestors
    RELIC_RELIC_OF_TORNADO, // RelicRelicOfTornado
    RELIC_GLAUCUS_BOOK_OF_PROPHECIES, // RelicGlaucusBookOfProphecies
    RELIC_PROW_OF_THE_ARGO, // RelicProwOfTheArgo
    RELIC_GOLDEN_CAMEL_STATUE, // RelicGoldenCamelStatue
    RELIC_XUAN_YUAN_SWORD, // RelicXuanYuanSword
    RELIC_ORACLE_BONE, // RelicOracleBone
    RELIC_ONIKIRI_DEMON_SLAYER, // RelicOnikiriDemonSlayer
    RELIC_FRAGMENT_OF_THE_KILLING_STONE, // RelicFragmentOfTheKillingStone
    RELIC_HODERIS_LOST_FISH_HOOK, // RelicHoderisLostFishHook
    RELIC_DECEPTIVE_WOODEN_SWORD, // RelicDeceptiveWoodenSword
    RELIC_SHACHIHOKO_ORNAMENT, // RelicShachihokoOrnament
    RELIC_CARTOGRAPHERS_HOURGLASS, // RelicCartographersHourglass
    FLAMING_WEAPONS_ACTIVE, // FlamingWeaponsActive
    ECLIPSE_ACTIVE, // EclipseActive
    LIGHTNING_WEAPONS_ACTIVE, // LightningWeaponsActive
    SHINBOKU_RESPAWN_ENABLE, // ShinbokuRespawnEnable
    VILLAGER_DWARF_TO_BERSERK, // VillagerDwarfToBerserk
    VILLAGER_NORSE_TO_BERSERK, // VillagerNorseToBerserk
    VILLAGER_ATLANTEAN_TO_HERO, // VillagerAtlanteanToHero
    ORACLE_TO_HERO, // OracleToHero
    KATAPELTES_TO_HERO, // KatapeltesToHero
    TURMA_TO_HERO, // TurmaToHero
    MURMILLO_TO_HERO, // MurmilloToHero
    CHEIROBALLISTA_TO_HERO, // CheiroballistaToHero
    CONTARIUS_TO_HERO, // ContariusToHero
    ARCUS_TO_HERO, // ArcusToHero
    DESTROYER_TO_HERO, // DestroyerToHero
    FANATIC_TO_HERO, // FanaticToHero
    MILITARY_CAMP_TO_TOWER, // MilitaryCampToTower
    MILITARY_CAMP_TO_TRAINING_YARD, // MilitaryCampToTrainingYard
    MILITARY_CAMP_TRAINING_YARD_TO_TOWER, // MilitaryCampTrainingYardToTower
    MILITARY_CAMP_TOWER_TO_TRAINING_YARD, // MilitaryCampTowerToTrainingYard
    MACHINE_WORKSHOP_TO_TOWER, // MachineWorkshopToTower
    MACHINE_WORKSHOP_TO_TRAINING_YARD, // MachineWorkshopToTrainingYard
    MACHINE_WORKSHOP_TRAINING_YARD_TO_TOWER, // MachineWorkshopTrainingYardToTower
    MACHINE_WORKSHOP_TOWER_TO_TRAINING_YARD, // MachineWorkshopTowerToTrainingYard
    WALL_CONNECTOR_TO_TOWER, // WallConnectorToTower
    GIANT_SLAYING_BLADES, // GiantSlayingBlades
    OSMIUM_ARMOR, // OsmiumArmor
    ASBESTOS_SHIELDS, // AsbestosShields
    SUDDEN_DEATH_START, // SuddenDeathStart
    SUDDEN_DEATH_CITADEL_NOMAD, // SuddenDeathCitadelNomad
    ULTRA_FAST_TRAINING, // UltraFastTraining
    ULTRA_HUNTABLE_RESOURCES, // UltraHuntableResources
    BROKKS_PRIMACY, // BrokksPrimacy
    THE_IRON_FORTRESS, // TheIronFortress
    THE_ETERNAL_PILLAR, // TheEternalPillar
    SPC_ENABLE_VFX, // SPCEnableVFX
    SPC_YASUKO_SUNBEAM_SHADOW, // SPCYasukoSunbeamShadow
    QINGHAI_LAKE_HITPOINTS_BONUS, // QinghaiLakeHitpointsBonus
    QINGHAI_LAKE_DAMAGE_BONUS, // QinghaiLakeDamageBonus
    QINGHAI_LAKE_GATHER_RATE_BONUS, // QinghaiLakeGatherRateBonus
    CHEAT_FOOTY, // CheatFooty
    CHEAT_BIG_OSIRIS, // CheatBigOsiris
    CHEAT_BIG_KRONOS, // CheatBigKronos
    CHEAT_BIG_PROMETHEUS, // CheatBigPrometheus
    CHEAT_BIG_GAIA, // CheatBigGaia
    CHEAT_IDLE_BOLT, // CheatIdleBolt
    DUMMY_AGE_UP_TECH, // DummyAgeUpTech
    LUDICROUS_MODE_GENERAL, // LudicrousModeGeneral
    CHEAT_BIG_CHIYOU, // CheatBigChiyou
}
